### ISSUE TITLE
Re: Travis issues

### ISSUE THREAD

**Issue by SolalPirelli** [karimassi/balelec-bud#44]
@karimassi (or anyone else), can you post a link of a specific Travis build that failed because of this simultaneous builds issue? It would help us figure out what's going on.

**Comment by karimassi** [comment]
I reran the build so the log isn't available anymore. If it happens again (it probably will) I'll comment on this issue with the affected link. 

I disabled the option "Auto cancel branch builds" and "Auto cancel PR builds". I don't think it is the problem (since it cancels the build but doesn't fail them), but it's worth the try.
